import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Penetration Tester & SOC Analyst Tier 2",
    company: "X-code (PT. Teknologi Server Indonesia)",
    logo: "/images/Logo-Xcode.jpg",
    location: "Daerah Istimewa Yogyakarta, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2025-08",
    end_date: "2025-09",
    industry: "Cyber Security / Information Technology",
    link: null,
    responsibilities: [
      "Investigated and mitigated cyber security threats to create a safer IT environment.",
      "Conducted penetration testing and vulnerability assessments to help the company proactively address security gaps.",
      "Supported SOC Tier 2 operations by analyzing alerts and incidents to protect critical infrastructure.",
      "Enhanced practical knowledge in SIEM, IDS/IPS, and cyber security frameworks.",
    ],
    isShow: true,
  },
  {
    position: "Information Technology Assistant",
    company: "Kominfo",
    logo: "/images/Logo-KOMINFO.png",
    location: "Sleman, Daerah Istimewa Yogyakarta, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2025-06",
    end_date: "2025-07",
    industry: "Government / Information Technology",
    link: null,
    responsibilities: [
      "Provided technical support and troubleshooting for IT systems, networks, and applications.",
      "Assisted in the maintenance, configuration, and monitoring of hardware and software infrastructure.",
      "Supported IT project implementations and initiatives to improve operational efficiency.",
    ],
    isShow: true,
  },
  {
    position: "Network Operations Center",
    company: "PT. Broadband Indonesia Pratama",
    logo: "/images/Logo-BIPNET.png",
    location: "Daerah Istimewa Yogyakarta, Indonesia 🇮🇩",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2023-01",
    end_date: "2023-04",
    industry: "Telecommunications / Network",
    link: null,
    responsibilities: [
      "Installed, configured, and maintained network devices across multiple locations.",
      "Managed cable installations, routers, and switches to ensure optimal connectivity.",
      "Assisted with network troubleshooting and provided technical support to users.",
    ],
    isShow: true,
  },
];
